sentriz/gonic

mime/mime.go
Mimetype defined in RFC7845 https://tools.ietf.org/html/rfc7845#section-9
Confirmed working with Audinaut.
=> Add opus support

go.mod
github.com/jinzhu/gorm v1.9.9 is vulnerable. Please see details here and update to secured one :
https://search.gocenter.io/github.com~2Fjinzhu~2Fgorm/info?version=v1.9.9
=> Security fix for github.com/jinzhu/gorm

server/ctrlsubsonic/spec/spec.go
This attribute is required as per spec and keeping it empty,
complies the spec as long as articles are not ignored while indexing.
In the future, this could maybe be a user setting that could be
supported.
With this change, the aurial client works now.
* https://shrimpza.github.io/aurial/
* https://github.com/shrimpza/aurial
=> spec: add IgnoredArticles attribute to Index responses

go.mod, go.sum
Hi, newer versions of oto allow for building on FreeBSD and OpenBSD.
This PR bumps oto and allows gonic to run on OpenBSD!
`go mod tidy` was run.
=> Bump oto to allow building on OpenBSD

server/ctrlsubsonic/handlers_common.go, server/server.go
Bugs this fixes:
* When you call `createPlaylist`, it is supposed to replace all of the IDs in the playlist with the IDs sent in the request. Gonic doesn't do that, instead, it appends the IDs. This is problematic for re-ordering songs in playlists in Sublime Music, since Sublime Music just sends an updated list of all of the song IDs in the playlist. The result is that all of the existing songs are duplicated in the playlist.
This PR also makes `createPlaylist` and `updatePlaylist` adhere to v1.14.0 spec:
* As of Subsonic API version 1.14.0, the updated playlist should be returned by the `createPlaylist` endpoint.
=> Fix bug in createPlaylist and make createPlaylist and updatePlaylist adhere to v1.14.0 spec

server/ctrlsubsonic/handlers_by_tags.go
DSub will error out in Artists views if browse by tags is enabled
and getArtistInfo2 returns an error.
=> Empty getArtistInfo2 response if lastfm_api_key is not set

server/ctrlsubsonic/handlers_raw.go, server/encode/encode.go
I made changes to the transcoding decisions to accommodate client requests. This is to avoid transcoding lossy file formats like mp3s when not necessary.
The logging is pretty verbose to show what is going on, feel free to remove it.
**Example 1**. The client  requests bitrate less than 320k, requested file is FLAC
```
2020/09/20 11:00:32 client requests 320k, transcoding profile 128k, track bitrate 572k
2020/09/20 11:00:32 Transcoding according to client request of 320k
2020/09/20 11:00:32 serving transcode `03 Lucky To Be Me.flac`: cache [mp3/320k] miss!
```
The client preference (320k) takes precedence over the server profile (128k) setting. This effectively dynamically adapts the transcoding profile to what the client wants.
**Example 2**. The client  requests bitrate less than 320k, …
=> Revamp the transcoding decision tree

server/encode/encode.go
At the moment Gonic writes data that comes from `ffmpeg` to cache files right away, and it may result in incomplete cache files (e.g. if either `ffmpeg` or Gonic crash mid-transcode). This PR adds a fairly stupid workaround: write to a `.part` file and rename it after it's been written to successfully.
=> Mark cache files as partial until `ffmpeg` finishes without errors

server/ctrlsubsonic/spec/construct_by_tags.go, server/ctrlsubsonic/spec/spec.go, server/ctrlsubsonic/testdata/test_get_album_with_cover
Hello,
This commit adds the album TagYear to the year field of every TrackChilds (when using tag browsing).
This allows implementations that don't support the Year field of albums (introduced in Subsonic 1.10.1) to derive the album year anyways. For information [Ultrasonic](https://github.com/ultrasonic/ultrasonic) behaves like this. 
In my setup I only use the tag browsing, but I think it might be useful to add it to NewTCTrackByFolder:construct_by_folder:39 as well. Tell me if you want me to add it to the PR.
Thanks with your work on this project otherwise, it's very nice !
=> Add year to TrackChilds of an Album

.github/workflows/go.yml, .github/workflows/image.yml
This requires the maintainer setting the DOCKERHUB_USERNAME and DOCKERHUB_PASSWORD secrets in the workflow settings on this repo.
This also adds multiarch support for amd64 and arm64 images.
=> fix: add image building workload on tag creation

Dockerfile, Dockerfile.dev
When I pulled the latest `sentriz/gonic` from Docker Hub, my container failed to start because I didn't have anything mounted to `/podcasts`.  If we list `/podcasts` as a volume in the Dockerfile, docker should automatically create the directory if it doesn't exist.
I tested this change locally.
=> List /podcasts as a volume in dockerfiles

server/ctrladmin/handlers.go, server/ctrlsubsonic/handlers_podcast.go, server/podcasts/podcasts.go
this will check that if there is no type field in an enclosure that the url ends with an audio filename, if none of these are true, itll then check audio:content for an item and do those checks again.
this was reported to be an issue as episodes werent showing up in #117 which it should fix 
This will also fix feeds that dont contain a feed url not updating  also mentioned in #117
=> make finding podcast feed audio more robust and use user provided feed urls

cmd/gonic/main.go, server/server.go
This mainly useful if gonic runs behind a proxy where http requests are already logged and to reduce the noise in gonic logs.
=> add flag (-http-log) to disable http request logging

server/scanner/tags/tags.go
I have some re-released albums tagged with musicbrainz which sets the `date`/`year` to the date of the re-release and adds `original_date`/`original_year` to the initial release date.
I personally prefer to see the original dates when browsing my music, not sure if there is a case against it.
=> scanner/tags: prefer original_date over date

server/scanner/tags/tags.go
Sorry should have tested this before:
Real tag is `originaldate` and matches TDOR from taglib in id3v2:
https://github.com/taglib/taglib/blob/1644c0dd/taglib/mpeg/id3v2/id3v2frame.cpp#L338
originalyear does not exist.
=> scanner/tags: fix original date

.github/workflows/nightly-release.yaml
You mentioned how you thought about using a short hash instead of the longer one. This would do the trick. Although seems ugly, may be one of the work arounds. You could combine with another step if you'd like as well.
=> ci: use short hash

server/encode/encode.go, server/mime/mime.go
Hello! Thank you so much for a server that Just Works with 99% of my music collection.
Unfortunately I have a few ornery .wma files that gonic doesn't detect. I made a first pass at adding them to the mimetypes:
```patch
diff --git a/server/mime/mime.go b/server/mime/mime.go
index 63c8f93..91b6277 100644
--- a/server/mime/mime.go
+++ b/server/mime/mime.go
@@ -12,6 +12,7 @@ func FromExtension(ext string) (string, bool) {
"m4b":  "audio/m4b",
"ogg":  "audio/ogg",
"opus": "audio/ogg",
+        "wma":  "audio/x-ms-wma",
}
v, ok := types[ext]
return v, ok
```
and that gets them successfully scanned, at least.  However, most clients don't know how to decode wma files so I'd like to transcode them. And that's where I hit problems.
Seems that my wma files have embedded album art encoded as a …
=> Support WMA files, including those with embedded album art

server/encode/encode.go
Hello @sentriz, long time no see! :)
I was messing around with my encode profiles and found that in some cases (e.g. my music library) source files can have EBU R128 gain tags alongside ordinary ReplayGain tags. If we don't instruct `ffmpeg` to strip out these tags during RG-enabled transcoding, it can confuse some client apps into thinking that the track has ReplayGain tags and should be processed accordingly. 
The main problem is that these R128 tags have a different scale than normal RG ones, and even when left with a value of `0` (zero) it can cause some clients to forcibly apply a whopping +5.0 dB gain to the track, causing clipping and occasional ear bleeding. :)
This PR fixes it by stripping these tags out. I double-checked the result (with `mediainfo` and Foobar2000) and now there …
=> Strip EBU R128 gain tags when using forced-RG transcoding

server/ctrlsubsonic/handlers_raw.go
This PR adds a simple MIME-type guessing logic to `onCacheHit` and `onCacheMiss` handlers, which sets `Content-Type` HTTP response header based on format specified by transcoding profile. It also sets `Content-Length` header, but only on cache hit (as we can't reliably know response length on cache miss, because VBR is a thing).
=> Add MIME-type and content length hints to cache handlers

go.mod, go.sum, server/jukebox/jukebox.go
Hello
This reduces some of the jukebox complexity and after testing it for a bit it all seems to be working quite a bit better. It also enables support for flac seeking by updating the dependencies.
=> feat(jukebox): reduce complexity and update dependencies

README.md
In reference to #185, clarifies that all files from an album must be in the same directory and the directory must only contain files from that album.
fixes #185
=> Updated README.md to clarify directory structure

server/assets/pages/home.tmpl
Currently there's no way to tell if a scan is running without looking at the logs. Now there is 😄
=> Show if a scan is running.

server/ctrlsubsonic/handlers_playlist.go, server/db/migrations.go, server/db/model.go
When multiple people share the same instance, they might want to share
their playlists between them.
This allows people to mark playlists as public, and to listen to public
playlists from other people. Listeners will also know who owns the
playlist, to help avoid confusion and make this feature a bit nicer.
Subsonic restrict updating playlists only to owners, this honors that
behavior, but adding flexibility could be achieved easily.
=> Support public playlists

server/server.go
I'm trying to reduce idle disk activity on my install, and so I want to configure my loadbalancer to check an endpoint that doesn't trigger a new session creation in the database.
=> Add a ping endpoint that doesn't create a session

README.md
There's an [undocumented http logging setting](https://github.com/sentriz/gonic/blob/7d0d036f0bc0f5bd4429f510ca636daa3934766b/cmd/gonic/gonic.go#L42) which I found useful to disable, and perhaps others might find it useful too.
=> Add GONIC_HTTP_LOG setting to README

server/ctrlsubsonic/handlers_by_folder.go, server/ctrlsubsonic/handlers_by_tags.go, server/ctrlsubsonic/handlers_common.go, server/ctrlsubsonic/handlers_playlist.go, server/ctrlsubsonic/spec/spec.go, transcode/transcode.go
This fixes a problem stated in the second comment of #106
The problem was that gonic didn't send the TranscodedContentType and TranscodedSuffix attributes when building the album list, playlist, etc... So the clients like DSub used the "suffix" xml attribute as the file suffix even if the file was being transcoded to another format.
Sorry if the code is somewhat "dirty". I don't know the project very well and it's my first time trying to fix something in go.
Feel free to fix any mistakes or re-implement it if you deem it necessary.
The fix builds and works with folder-browsing, tag-browsing and with and without a transcode profile.
=> Fix the file extension when transcoding

scrobble/lastfm/lastfm.go, scrobble/listenbrainz/listenbrainz.go
since some people may have a non musicbrainz uuid in the tag's place. eg with the discogs/lastfm plugins for beets.io
=> feat(scrobble): only send musicbrainz id if it's a valid uuid

scanner/scanner.go
Fixes: https://github.com/sentriz/gonic/issues/287
```golang
fileInfo, err := os.Stat(event.Name)
if err != nil && fileInfo.IsDir()
```
This statement is meaningless because if error is not empty then fileInfo be always empty. It causes panic which is mentioned in the issue.
My solution is just skip cycle if file moved or deleted during the scan.
=> Fix watcher panic

transcode/transcode.go
This diff adds the 192kbps OPUS transcoding profile named opus_audiophile. While 128kbps is already near transparent and good for most use cases, sometimes (or by some people) a bit more is preferred. These are typically for dedicated high quality wireless audio link (A2DP-bluetooth) enabled headphones and Hi-Fi adapters.
The 160-192kbps range is considered to be transparent with very low chance of artifacts (only with very few and specific samples)[1][2].
[1] https://wiki.hydrogenaud.io/index.php?title=Opus
[2] https://ceur-ws.org/Vol-2654/paper25.pdf
=> Add "audiophile" transcode profile

README.md
- Sublime music: update link as it has moved to GitHub
- Add Strawberry music player (Clementine fork) for QT and KDE desktops
- Add Ultrasonic Android app
=> docs: update tested on player list in README

README.md, cmd/gonic/gonic.go, mockfs/mockfs.go, scanner/scanner.go, scanner/scanner_test.go, server/server.go
This change adds a new `GONIC_EXCLUDE_PATTERN` option. Paths matching the given pattern will be skipped by the scanner.
closes #253
=> Feature: Add new option for excluding paths

Dockerfile, Dockerfile.dev
What?
=====
Add the `/playlists` directory to the list of volumes, so the server doesn't exit when validating the playlist path on startup.
Why?
=====
With the current behavior, the server process exits when no playlist directory is found, see: https://github.com/sentriz/gonic/blob/7dc9575e52538cf4fd39715193b5c760e1cc477b/cmd/gonic/gonic.go#L104
=> Bugfix: Add playlists directory to volumes

Dockerfile, Dockerfile.dev
This PR reverts commit aae06836715f4159ac5cacf83ae5c2d5e3e4f52f as the original change (see PR #314) might cause data loss for existing users if the `playlists` volume is not explicitly mapped to permanent storage.
=> Revert | Add playlists directory to docker volumes

.github/workflows/debug-release.yaml, .github/workflows/nightly-release.yaml, .github/workflows/release.yaml, .github/workflows/test.yaml
Update GitHub actions :
- Update [Checkout action](https://github.com/actions/checkout) to v3.
- Update [Setup-go](https://github.com/actions/setup-go) to v4.
- Get Go version from `go.mod`.
=> feat(ci): Update GitHub actions

podcasts/podcasts.go
This was causing me problems with the Equity podcast, which uses GUIDs as filenames.
=> Need to add a safeFilename call going into findUniqueEpisodeName.

server/ctrlsubsonic/spec/construct_podcast.go
If you're not going to take the change to make this a config option, then you should take this PR instead to parse podcast descriptions just as with podcast episodes, which is in that PR and is a good idea regardless IMO.
=> Parse podcast description from HTML to text just as with episodes.

db/migrations.go, db/model.go, fileutil/fileutil.go, fileutil/fileutil_test.go, podcasts/podcasts.go, podcasts/podcasts_test.go, podcasts/testdata/rss.new, server/ctrlsubsonic/ctrl_test.go, server/ctrlsubsonic/handlers_common.go, server/ctrlsubsonic/handlers_playlist.go, server/ctrlsubsonic/handlers_raw.go, server/ctrlsubsonic/spec/construct_by_folder.go, server/ctrlsubsonic/spec/construct_by_tags.go, server/ctrlsubsonic/spec/construct_podcast.go, server/ctrlsubsonic/specidpaths/specidpaths.go
- auto increment podcast names too
- store podcast root dirs (like we do for music)
- drop podcast episode "path" column
TODO:
fixes #350
=> refactor podcast filepaths

server/ctrlsubsonic/spec/spec.go
The `songCount` and `albumCount` attributes are required according the subsonic api xml file. Noticed this in the airsonic-refix client where the genres page would sort the genres wrong if the value is left out instead of 0.
=> fix(subsonic): songCount and albumCount in genre objects is required

cmd/gonic/gonic.go, scanner/scanner.go, scanner/scanner_test.go
hiya @brian-doherty , i was reading the scanner code again today, and since it had been a while it took me a little while to grasp it again. i'm wondering what you think about these changes that i've found to help a me a bit
- pass only an "absPath" arg to scanCallback and watchCallback instead of "absPath" and "dir" (musicDir). the callbacks can deduce the root dir themselves, and the two args have always been confusing, even for the original scanCallback
- delete the watch stuff from the main scanner struct. it seems we don't need watchMap given above^ and the others can be centralised to ExecuteWatch
- update some names so that its clear we're doing some event batching
thoughts? thanks!
=> refactor(scanner): make the watcher a little easier to reason about

listenbrainz/listenbrainz.go, listenbrainz/listenbrainz_test.go, listenbrainz/model.go, listenbrainz/testdata/submit_listens_request.json
This fixes the track length submission for ListenBrainz. ListenBrainz defines the fields `duration` and `duration_ms` for this, see https://listenbrainz.readthedocs.io/en/latest/users/json.html . Without this information LB will not show a track length. It might also prematurely remove the "now playing" notification for longer tracks.
As I understand from the code the track length is in seconds precision, hence the `duration` field is being used. `duration_ms`  would be for milliseconds.
This PR also includes the fields `submission_client` as defined in the LB API docs linked above.
=> Fix listenbrainz track length submission and include submission client details

cmd/gonic/gonic.go, db/db.go, podcast/podcast.go, server/ctrlsubsonic/handlers_by_folder.go
- drive download by a single download "event loop" thread
- controlled concurrency
- resume-on-restart downloads
- suspend gonic shutdown until current download is complete
- re-use pe filename as download destination to avoid .1 .1.1 .1.1.1 etc unique name
- update error status in more places
=> fix(podcast): slightly more robust downloading and concurrency

server/ctrlsubsonic/specidpaths/specidpaths.go
As discussed on IRC, if you have two paths like
```
/Music/Tagged
/Music/TaggedManual
```
it may grab the wrong musicPath from checking prefixes.
Add a `/` to the music path to ensure that the prefix is a real dir, and not a partial name to a dir
=> Fix bug with checking path prefixes

playlist/playlist.go
This is carrying on from the various tickets under which playlists have been discussed.
For reasons well-known (#306, #311, #307, #311... but mainly #306), the Subsonic API forces playlists to be by user ID. The solution in gonic was to expect a directory layout with `<playlistpath>/<userid>/.../<whatever>.m3u`. This is inconvenient for users for whom gonic is not the only application using the playlist directory, and maybe not even the main one, an inconvenience exacerbated by the fact that `fs.DirEntry.IsDir()` returns false for directory symlinks.
This extremely trivial change does one thing: instead of throwing an error when the directory structure does not contain user IDs as the second element in the path, it merely adds those playlists to the admin's playlist list. This change has …
=> Add playlists with no user to admin's playlist list.

Dockerfile
Without this, abuild refuses to run correctly:
```
29.52 (33/33) Purging gmp (6.3.0-r0)
29.52 Executing busybox-1.36.1-r19.trigger
29.52 OK: 17 MiB in 37 packages
29.55 >>> taglib2: Updating the /x86_64 repository index...
29.56 ERROR: libtag-2.0.1-r0.apk: UNTRUSTED signature
29.56 ERROR: libtag_c-2.0.1-r0.apk: UNTRUSTED signature
29.56 ERROR: taglib2-2.0.1-r0.apk: UNTRUSTED signature
29.56 ERROR: taglib2-dev-2.0.1-r0.apk: UNTRUSTED signature
29.56 >>> ERROR: taglib2: Failed to create index
29.56 >>> taglib2: Uninstalling dependencies...
29.73 ERROR: No such package: .makedepends-taglib2
------
8 warnings found (use --debug to expand):
- LegacyKeyValueFormat: "LABEL key=value" should be used instead of legacy "LABEL key value" format (line 30)
- LegacyKeyValueFormat: "ENV key=value" …
```
=> fix(dockerfile): install abuild key

playlist/playlist.go, server/ctrlsubsonic/handlers_playlist.go
Found this while working on a tentative implementation for #522. It seems that https://github.com/sentriz/gonic/pull/499 introduced some logic that prepopulates `playlist.UserID` to `1` if nothing else can be decoded from the path.
Before this PR, `ServeCreateOrUpdatePlaylist` was trying to figure out if a playlist existed by trying to open the file derived from its name. If the name does not exist, `playlistIDDecode` returns an empty string, which `playlistStore.Read` gladly accepts and proceeds to open `""`, which implies `.`, which does not fail. Then, the code added in #499 will slap the admin user ID on the playlist object, shortly before `playlistStore.Read` realizes this is actually a directory and returns an error.
That error, however, was never checked. As a result, an empty …
=> Fix non-admin users not being able to create playlists

server/ctrlsubsonic/handlers_raw.go
This fixes a typo on a log message, and another on a function name.
Heads up for the log message: although I think it's better to have it correctly, it would impact anyone using this downstream.
For example, I found this while creating a filter on grafana to see how often transcodings were happening. For anyone who has already setup, either something similar or anything that relies on that log message, they'll have to update their configuration.
I don't know if that's even happening, since maybe that would have resulted on this same change before, but wanted to make sure we are aware of that.
=> Fix transcoding typos

db/db.go, db/migrations.go, podcast/podcast.go
This will use the podcast author if the podcast episode author is `undefined`. Should fix the issue stated in https://github.com/sentriz/gonic/issues/565.
=> Use podcast author if episode author is not defined.

server/ctrlsubsonic/handlers_bookmark.go
Currently if a bookmark exists for an item that does not exist in the db, either because it has been removed or it never did, the user is prevented from retrieving any bookmarks. We can be in this state if media has moved or been deleted, but also because the createBookmark endpoint does not verify the item id provided.
This patch makes the getBookmarks endpoint ignore bookmarks for missingitems.
Fixes: https://github.com/sentriz/gonic/issues/578
=> Skip bookmarks for missing items instead of failing
