README.md

add default login info, clarify interface

---

mime/mime.go

Fixes https://github.com/sentriz/gonic/issues/29

Add m4b mimetype.

---

db/db.go
db/migrations.go
db/model.go
scanner/scanner.go
scanner/tags/tags.go
server/ctrlsubsonic/handlers_by_tags.go
server/ctrlsubsonic/handlers_common.go
server/ctrlsubsonic/handlers_unimplemented.go
server/ctrlsubsonic/spec/construct_by_tags.go
server/ctrlsubsonic/spec/spec.go
server/server.go

I never used gomigrate, so I'm not sure if this is correct.
This also adds a decoded name column to the genres table, I thought there was a indexed genre but there isn't I can remove the column if you think its not necessary.
closes #34

add getGenres support

---

server/jukebox/jukebox.go

This seems to be how its supposed to be implemented
set - should only change current playlist and shouldnt modify index
This lets dsub work properly when it comes to modifying the current
playlist as it does a combination of "set" and "skip"
Itll only use set if its adding tracks to the playlist and includes
the whole playlist, and itll use both set and skip to set the current
playing and skip back to the first track

Improve compatibility with the subsonic api

---

README.md

Update README formatting and made the issues and pull request badges actually go to the Issues and Pull requests pages.
Also removed leading space at the front of all of the lines in the README because I have OCD.

Update README formatting and badges

---

server/ctrlsubsonic/spec/construct.go
server/ctrlsubsonic/spec/spec.go

Closes #74 
I think this works, but I am no expert in Go.

Make duration adhere to the spec

---

cmd/gonic/main.go
go.mod
go.sum
server/ctrlsubsonic/ctrl.go
server/ctrlsubsonic/handlers_raw.go
server/server.go

This uses a default width of 600 which is what airsonic uses.
As format png is used which could be changed to jpg, I don't really have a preference.
The default compression level is used, this could be changed to better speed or better compression.

add album cover scaling and caching

---

README.md

stmp is a terminal based subsonic client. I've developed it specifically for use with gonic.

Add stmp to supported clients

---

server/ctrlsubsonic/handlers_common.go
server/jukebox/jukebox.go

Currently beep doenst support seeking with flac but it does with mp3 and (presumably wav) so it doesnt work but once https://github.com/mewkiz/flac/pull/43 merges it should be easy to add support for it to beep

Jukebox Improvments: Support seeking, fix the default returned return api type

---

Dockerfile

Add the `tzdata` alpine package for configuring timezone

feature: allow configuring timezone

---

Dockerfile

tini is a neat little `init`
https://github.com/krallin/tini
Benefits? See here
https://github.com/krallin/tini/issues/8

feature: add tini to dockerfile

---

server/db/model.go
server/podcasts/podcasts.go

https://github.com/sentriz/gonic/issues/117#issuecomment-780971049
[failure is due to linting timing out, but i get nothing locally]

Fix podcasts with / in the name/episode title

---

README.md

Updated the link to the Sublime Music project.

update sublime-music link

---

server/ctrlsubsonic/ctrl.go
server/ctrlsubsonic/ctrl_test.go
server/ctrlsubsonic/handlers_by_folder.go
server/ctrlsubsonic/handlers_by_folder_test.go
server/ctrlsubsonic/handlers_by_tags.go
server/ctrlsubsonic/handlers_by_tags_test.go
server/ctrlsubsonic/handlers_common.go
server/ctrlsubsonic/spec/spec.go
server/mockfs/mockfs.go
server/scanner/scanner_test.go
server/server.go

https://github.com/sentriz/gonic/issues/50#issuecomment-963257103
https://github.com/einsteinx2/iSubMusicStreamer/blob/006c1dafee6b926fde9d775cb0e64011a4662853/Classes/Models/API%20Models/MediaFolder.swift#L16
related #50

make `musicFolderId`s ints

---

server/ctrladmin/ctrl.go
server/ctrladmin/handlers.go
server/ctrlsubsonic/handlers_playlist.go
server/ctrlsubsonic/middleware.go
server/ctrlsubsonic/params/params.go
server/encode/encode.go
server/mockfs/mockfs.go
server/scanner/scanner.go
server/scanner/scanner_test.go
server/server.go

follow symlinks and cleanup

---

server/ctrladmin/handlers.go
server/ctrlsubsonic/handlers_by_folder.go
server/scanner/scanner.go

feat: use album create time for home ui and album listings

---

server/ctrlsubsonic/handlers_by_tags.go

Hey there
I made the following improvement to ```/getArtistInfo2```
I realized that, as  ```lastfm.artist.getInfo``` as only retrieving a couple of artist, ```/getArtistInfo2``` was most of the time returning very few (or no) similar artists. 
- Retrieve similar artists using ```lastfm.artist.getSimilar``
- Match similar artists result with internal database in one single sql query, using a similar pattern as we used for ``` ServeGetSimilarSongs``` and ```ServeGetSimilarSongsTwo```

Improve how subsonic ServceGatArtistInfoTwo is retrieving similar artist

---

.gitignore
db/migrations.go
db/model.go
server/assets/pages/home.tmpl
server/ctrladmin/ctrl.go
server/ctrladmin/handlers.go
server/ctrlsubsonic/ctrl_test.go
server/ctrlsubsonic/handlers_internet_radio.go
server/ctrlsubsonic/handlers_internet_radio_test.go
server/ctrlsubsonic/handlers_podcast.go
server/ctrlsubsonic/spec/construct_internet_radio.go
server/ctrlsubsonic/spec/spec.go
server/ctrlsubsonic/specid/ids.go
server/server.go

Added Internet radio support. Will continue adding test cases but basic functionality works as verified by hand using DSub.

Internet radio support

---

cmd/gonic/gonic.go
paths/paths.go
server/ctrlsubsonic/ctrl.go
server/ctrlsubsonic/ctrl_test.go
server/ctrlsubsonic/handlers_common.go
server/server.go

feat: allow for custom music folder path alias

---

db/model.go
mime/mime.go
podcasts/podcasts.go
scanner/scanner.go

fix(subsonic): send valid content-type with http.ServeFile

---

contrib/config
contrib/gonic.service
contrib/gonic.sysusers
contrib/gonic.tmpfiles

- Make gonic configuration self documenting
- Update systemd files

feat(contrib): improve system related contrib files

---

mime/mime.go

Add .wav to list of supported audio types

---

podcasts/podcasts.go

Rename podcast and podcast episode filenames to be safe at startup.

---

server/ctrlsubsonic/handlers_playlist.go
server/ctrlsubsonic/specidpaths/specidpaths.go

Fix return playlist if file not found and do not add to playlist not downloaded podcast.
fixes #345

Fix return playlist

---

transcode/transcode.go

Adds `mp3_320` transcoding profile for MPEG MP3 @ 320kpbs. 
Closes: #362

Added MP3 320 transcoding profile

---

mime/mime.go

addd wavpack to supportted audio types

addd wavpack to supportted audio types

---

server/ctrlsubsonic/handlers_common.go
server/ctrlsubsonic/handlers_raw.go
transcode/transcode_test.go
transcode/transcoder_caching.go

as per
https://github.com/opensubsonic/open-subsonic-api/pull/54
https://github.com/opensubsonic/open-subsonic-api/discussions/21

feat(subsonic): support timeOffset in stream.view

---

README.md

Fix links to multi-valued-tags

---

podcast/podcast.go

fixes https://github.com/sentriz/gonic/issues/546

fix(podcast): nil pointer when podcast has no image

---

scanner/scanner.go

Currently, if a media item (track or podcast episode) is removed the entries in the bookmark table that refer to the now missing media item are left in the table. This commit adds a cleanup method which is part of the scan.

Cleanup bookmarks on scan
